// generated by cdktf get
Object.defineProperty(exports, 'branch', { get: function () { return require('./branch'); } });
Object.defineProperty(exports, 'project', { get: function () { return require('./project'); } });
Object.defineProperty(exports, 'settings', { get: function () { return require('./settings'); } });
Object.defineProperty(exports, 'dataSupabaseApikeys', { get: function () { return require('./data-supabase-apikeys'); } });
Object.defineProperty(exports, 'dataSupabaseBranch', { get: function () { return require('./data-supabase-branch'); } });
Object.defineProperty(exports, 'dataSupabasePooler', { get: function () { return require('./data-supabase-pooler'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });

