name: 🔧 Technical Debt / Infrastructure
description: Technical improvements, refactoring, or infrastructure work
title: "[Tech] "
labels: ["type:tech-debt"]
body:
  - type: markdown
    attributes:
      value: |
        ## Technical Debt / Infrastructure Work
        Use this template for technical improvements, refactoring, infrastructure setup, or other non-feature work.
        
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What type of technical work is this?
      options:
        - Infrastructure (database, deployment, monitoring)
        - Performance (optimization, caching, queries)
        - Code Quality (refactoring, testing, documentation)
        - Security (authentication, validation, permissions)
        - Developer Experience (tooling, workflow, automation)
        - Dependencies (updates, migration, compatibility)
    validations:
      required: true
      
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What technical issue needs to be addressed?
      placeholder: "Describe the current problem or limitation..."
    validations:
      required: true
      
  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: How should this be addressed?
      placeholder: "Describe the proposed technical approach..."
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this work?
      options:
        - High (blocking other work)
        - Medium (important but not urgent)
        - Low (nice to have)
    validations:
      required: true
      
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: What will improve after this work?
      placeholder: "Performance gains, maintainability, developer productivity, etc."
    validations:
      required: false
      
  - type: textarea
    id: risks
    attributes:
      label: Risks & Dependencies
      description: Any risks or dependencies for this work?
      placeholder: "Breaking changes, external dependencies, etc."
    validations:
      required: false