// generated by cdktf get
Object.defineProperty(exports, 'customDomain', { get: function () { return require('./custom-domain'); } });
Object.defineProperty(exports, 'environment', { get: function () { return require('./environment'); } });
Object.defineProperty(exports, 'project', { get: function () { return require('./project'); } });
Object.defineProperty(exports, 'service', { get: function () { return require('./service'); } });
Object.defineProperty(exports, 'serviceDomain', { get: function () { return require('./service-domain'); } });
Object.defineProperty(exports, 'sharedVariable', { get: function () { return require('./shared-variable'); } });
Object.defineProperty(exports, 'tcpProxy', { get: function () { return require('./tcp-proxy'); } });
Object.defineProperty(exports, 'variable', { get: function () { return require('./variable'); } });
Object.defineProperty(exports, 'variableCollection', { get: function () { return require('./variable-collection'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });

