// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/daily": {
    params: {};
  };
  "/wpm": {
    params: {};
  };
  "/ducks": {
    params: {};
  };
  "/diff": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/daily" | "/wpm" | "/ducks" | "/diff";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/daily.tsx": {
    id: "routes/daily";
    page: "/daily";
  };
  "routes/wpm.tsx": {
    id: "routes/wpm";
    page: "/wpm";
  };
  "routes/ducks.tsx": {
    id: "routes/ducks";
    page: "/ducks";
  };
  "routes/diff.tsx": {
    id: "routes/diff";
    page: "/diff";
  };
};